{% set name = "rollup" %}
{% set version = "4.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rollup/rollup/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 25d664ddacec54db8ed5c14b69dd7968258142f197f0775184527782ab515125

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - make
    - nodejs
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - rollup --help

about:
  home: https://github.com/rollup/rollup
  summary: 'Rollup is a module bundler for JavaScript which compiles small pieces of code into something larger and more complex, such as a library or application.'
  description: |
    Rollup is a module bundler for JavaScript which compiles small pieces of code
    into something larger and more complex, such as a library or application.
    It uses the standardized ES module format for code, instead of previous idiosyncratic
    solutions such as CommonJS and AMD. ES modules let you freely and seamlessly combine
    the most useful individual functions from your favorite libraries. Rollup can
    optimize ES modules for faster native loading in modern browsers, or output a legacy
    module format allowing ES module workflows today.
  license: MIT
  license_file:
    - LICENSE.md
    - ThirdPartyLicenses.txt
  doc_url: https://rollupjs.org/

extra:
  recipe-maintainers:
    - MementoRC
